---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: zwavejs/zwave-js-ui
      tag: 8
    env:
      TZ: "America/New_York"
    resources:
      requests:
        memory: 200Mi
        cpu: 50m
      limits:
        memory: 500Mi
    service:
      main:
        ports:
          http: 
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
        - host: "z.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "z.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        mountPath: /usr/src/app/store
        accessMode: ReadWriteOnce
        size: "1Gi"
        skipuninstall: true
      usb:
        enabled: true
        type: hostPath
        hostPath: '/dev/serial/by-id/usb-Silicon_Labs_Zooz_ZST10 700_Z-Wave_Stick_0001-if00-port0'
        hostPathType: CharDevice
