---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: snapshot-controller
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: piraeus
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    replicaCount: 3
    serviceMonitor:
      create: true
