---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.14
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883
    auth:
      enabled: true
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            listener 1883
            allow_anonymous true
            persistence false
            connection_messages false
    persistence:
      config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      data:
        enabled: true
        existingClaim: mosquitto-config-v1
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto
    resources:
      requests:
        cpu: 5m
        memory: 10M
      limits:
        memory: 10M
