apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    env:
      TZ: America/New_York
    image:
      repository: homeassistant/home-assistant
      tag: '2023.12'
    service:
      main:
        ports:
          http:
            port: 8123
    probes:
      startup:
        enabled: false
      readiness:
        enabled: true
      liveness:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "home.${SECRET_DOMAIN}"
            secretName: home-tls
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      usb:
        enabled: true
        type: hostPath
        hostPath: /run/dbus